#!/bin/bash 

/usr/local/jdk_se7/bin/java -cp /usr/local/jmlunitng-1.4/lib/jmlunitng.jar:/usr/local/jmlunitng-1.4/org.jmlspecs.OpenJMLUI_0.5.33/jmlruntime.jar:testbin com.beust.testng.TestNG test_movePlayer.xml